pipeline {
  agent any
stages {
stage ('Compiler Stage') {
steps {
  withAnt(ant : stage('apache-ant-1.10.3') {
     sh 'ant war'
}
}
}
stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
}
}
            
              
 


